// AUTO-GENERATED by scripts/convert-marginalia.mjs — do not edit.

import inkAsset1 from './walkman-boy.svg'
import inkAsset2 from './walkman-boy.player.svg'
import inkAsset3 from './walking-woman.svg'
import inkAsset4 from './walking-woman.tote.svg'
import inkAsset5 from './reading-woman.svg'
import inkAsset6 from './reading-woman.cup.svg'

export type InkPart = {
  src: string
  class: string
  topPct: number
  leftPct: number
  widthPct: number
  heightPct: number
}

export type InkCharacter = {
  base: string
  parts: InkPart[]
}

export const INK_WALKMAN_BOY: InkCharacter = {
  base: inkAsset1,
  parts: [
    { src: inkAsset2, class: 'ink-part--player', topPct: 82.957, leftPct: 3.019, widthPct: 28.986, heightPct: 14.536 }
  ],
}
export const INK_WALKING_WOMAN: InkCharacter = {
  base: inkAsset3,
  parts: [
    { src: inkAsset4, class: 'ink-part--tote', topPct: 50.776, leftPct: 5.394, widthPct: 25.89, heightPct: 37.612 }
  ],
}
export const INK_READING_WOMAN: InkCharacter = {
  base: inkAsset5,
  parts: [
    { src: inkAsset6, class: 'ink-part--cup', topPct: 35.095, leftPct: 0, widthPct: 20.423, heightPct: 17.331 }
  ],
}
